{% set name = "adal" %}
{% set version = "1.0.2" %}
{% set sha256 = "4c020807b3f3cfd90f59203077dd5e1f59671833f8c3c5028ec029ed5072f9ce" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - pyjwt >=1.0.0
    - requests >=2.0.0
    - python-dateutil >=2.1.0
    - cryptography >=1.1.0

test:
  imports:
    - adal

about:
  home: https://github.com/AzureAD/azure-activedirectory-library-for-python
  license: MIT
  license_family: MIT
  summary: |
    The ADAL for Python library makes it easy for python application to authenticate 
    to Azure Active Directory (AAD) in order to access AAD protected web resources.
  
extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
