{% set name = "adal" %}
{% set version = "1.0.1" %}
{% set sha256 = "71b0e9b479320f76af4bcd268f7359580ba2e217228e83ff7529f51a9845f393" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - pyjwt >=1.0.0
    - requests >=2.0.0
    - python-dateutil >=2.1.0
    - cryptography >=1.1.0

test:
  imports:
    - adal

about:
  home: https://github.com/AzureAD/azure-activedirectory-library-for-python
  license: MIT
  license_family: MIT
  summary: |
    The ADAL for Python library makes it easy for python application to authenticate 
    to Azure Active Directory (AAD) in order to access AAD protected web resources.
  
extra:
  recipe-maintainers:
    - ivoflipse
    - Korijn
