travis:
  secure:
    BINSTAR_TOKEN: gkicyHDXyEiZaLQ8NcyT6zS+/pkOmb2GyQcUTX7SMPj1wWCDVXfrt5+GWdJFOWhU3T6p9NyCYrknFhURSDLDagphmX2jYNHleAYOPzPLmwOsv2R+Y2/v/+Zd6ImvkBjlCTeug+bydf0T1T4w8U2Wfjpb87phgK0toASG5uWXdhYPXN3dj7F6YvFxegvZ0ScEJW78f82m1cTtEqXLFqLMicfIKVVPSDjEpkF2bcNbLuwZU1eY7ou/uCl+LqAVEY/Ehn8sCFTHBwIVjSPGJdZeB15v/WnkyYGVWbEjm/YTPY2QDUrkX14uMyotEo8mroWfZjNpieTlrg4XtKwm6WKfP7s6UbxLL1GKbgOoT/olVHYPVGTuWiUCyDkYhKKiz9FHKnIqV2IyQzx2HZ2urHNIdh80BQz4XTz+ndRVYjRBlTipSqtp3uwrsniDNXkKfoZkOB9gWm2nSpYVXN6rHtS5sNI5+E7o8k6C5IMmpRzk87YB2w+8fyEFDpkfxivsoo029K/UOABTyhIra6KdhJWnXq64k6099FokrLslCHJeI1Whahn+ndils2tQJWD1ZO5u4Wp3o51iLlov5FhWwSB7ihxV1azIrKyszswDut+Mgo4Cpq1i6x7swlvURId1mZRUy2jnV9BQL1XhIrJRR4dKMSr3FQ80ZCuIOjvGZ+83DD8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
