travis:
  secure:
    BINSTAR_TOKEN: XM6DC02WTl/LJeYGlW8hX3MFLLtZwfKJHIbLmrWTAzlrg8rG1MnZjuIdYsYa+ySiIKmHnWB7daLc5Lc6u5eky3NPKA0L6Cm4C+jIAYf6jWMY7UOmbreA3phVV082CaGPlpZ/TBbPBBT1JvyyxDFX7M2uea+ww1dhQC+OJinvdQEuEOQoepN9zheivgwQMm9FpJvubNbTKRLFQgCcEqJb9JVas3etzjMastvPlPO/E7gf3pcwwTm2A2P/xv0eVZR2Pofk2fj6kNoHAvJ0AZoRSA5u37xU1N+hQn+ForQGHyxkI/Y4Kf1WBtFr/uzOyLxzvKt3fwOqugnm0uuZPboOE2jsOD58SKkqzyf8A24yTGuqQmdOPNCZOkZLaVIws/CVKa8OeINaomEypWW6P2mQ/7rtMfsImczMi2FN4RinD3cFnwPpYS+/wArHL/9yMp5wZqRWbJt3YUMfJws5V6qHddwQOwlcTfmGEO4FRP4NczhmTTQpA3kuGyx9fPQ/dbjnBhMC3SZ0lqWMlznNj9z+xuNR4Ty1t2CLQ5ln6V1xIbGWI01VLF833R0M5e4QQF05PNBAiVolvBR595s0B8Y5Ap6ohtmh3AF17fZnXRqXOBfgmNSKDluhDGdyMOKvbUkd+Ss/k3QfKtwFQqE43v3xJMCRF9kyyCsGAKOfNysKUs4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
